name: Deploy to Webdock

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployment_note:
        description: 'Deployment notes'
        required: false
        default: 'Manual deployment'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WEBDOCK_SSH_PRIVATE_KEY }}
          
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy directly to Webdock
        env:
          WEBDOCK_SERVER: ${{ secrets.WEBDOCK_SERVER }}
          WEBDOCK_USERNAME: ${{ secrets.WEBDOCK_USERNAME }}
          DEPLOY_PATH: ${{ secrets.WEBDOCK_DEPLOY_PATH || '/var/www/mail-checker' }}
        run: |
          # Get deployment timestamp
          DEPLOY_TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          DEPLOY_USER="${{ github.actor }}"
          
          # Deploy to server using rsync
          echo "Deploying code to Webdock..."
          rsync -avz --exclude='.git' --exclude='.github' --exclude='node_modules' \
            --exclude='tests' --exclude='coverage' --delete \
            ./ ${WEBDOCK_USERNAME}@${WEBDOCK_SERVER}:${DEPLOY_PATH}/

          # Execute post-deploy commands
          ssh ${WEBDOCK_USERNAME}@${WEBDOCK_SERVER} << EOF
            cd ${DEPLOY_PATH}
            
            # Update environment variables
            if [ -f .env ]; then
              # Update deployment info in .env
              sed -i '/DEPLOY_TIMESTAMP/d' .env
              sed -i '/DEPLOY_USER/d' .env
              echo "DEPLOY_TIMESTAMP=${DEPLOY_TIMESTAMP}" >> .env
              echo "DEPLOY_USER=${DEPLOY_USER}" >> .env
            else
              # Create .env if it doesn't exist
              echo "NODE_ENV=production" > .env
              echo "PORT=3000" >> .env
              echo "DEPLOY_TIMESTAMP=${DEPLOY_TIMESTAMP}" >> .env
              echo "DEPLOY_USER=${DEPLOY_USER}" >> .env
            fi
            
            # Install dependencies
            npm ci --production
            
            # Restart the application using PM2
            if pm2 list | grep -q "mail-checker"; then
              pm2 reload mail-checker --update-env
            else
              pm2 start server.js --name mail-checker
              pm2 save
            fi
            
            echo "Deployment completed at ${DEPLOY_TIMESTAMP}"
            EOF